### ISSUE TITLE
PackageManagerが落ちる

### ISSUE THREAD

**Issue by Cugry** [FloxoRom/manifesto#1]
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.getComponentEnabledSettingInternal(PackageManagerService.java:24620)
	at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:24603)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3307)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8928)
	at android.os.Binder.execTransactInternal(Binder.java:1179)

stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:1013)
Caused by: java.lang.IllegalArgumentException: Unknown component: ComponentInfo{com.google.android.settings.intelligence/com.google.android.settings.intelligence.modules.battery.impl.BatterySettingsContentProvider}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:7204)
	at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2814)
	at com.google.android.settings.fuelgauge.DatabaseUtils.isContentProviderEnabled(Unknown Source:13)
	at com.google.android.settings.fuelgauge.DatabaseUtils.getHistoryMap(Unknown Source:63)
	at com.google.android.settings.fuelgauge.PowerUsageFeatureProviderGoogleImpl.getBatteryHistory(Unknown Source:5)
	at com.android.settings.fuelgauge.BatteryChartPreferenceController.getBatteryLast24HrUsageData(BatteryChartPreferenceController.java:625)
	at com.android.settings.applications.appinfo.AppBatteryPreferenceController$1.doInBackground(AppBatteryPreferenceController.java:181)
	at com.android.settings.applications.appinfo.AppBatteryPreferenceController$1.doInBackground(AppBatteryPreferenceController.java:174)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.getComponentEnabledSettingInternal(PackageManagerService.java:24620)
	at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:24603)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3307)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8928)
	at android.os.Binder.execTransactInternal(Binder.java:1179)

**Comment by FloxoRom** [comment]
解決 : vendor_addonsにこのcommitが必要
https://github.com/crdroidandroid/android_vendor_addons/commit/aa15445554ba3b57125e053894b35450a878e353

**Comment by Cugry** [comment]
解決 : vendor_addonsにこのcommitが必要
https://github.com/crdroidandroid/android_vendor_addons/commit/aa15445554ba3b57125e053894b35450a878e353
